spring.application.name=utility-billing-system

spring.datasource.url=jdbc:postgresql://localhost:5432/ubs_db
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

server.port=8080

app.jwt.secret=change-this-secret-to-at-least-32-characters-for-production
app.jwt.expiration-minutes=1440

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kirezilivia@gmail.com
spring.mail.password=azud cvfk puvq kiat
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=kirezilivia@gmail.com
app.admin.email=kirezilivia@gmail.com
app.admin.bootstrap-password=Admin@12345
app.frontend.login-url=http://localhost:8080/swagger-ui.html

springdoc.swagger-ui.path=/swagger-ui.html
